"""Created customer data

Revision ID: 4416fe65c2ad
Revises: 70dd9f3704e6
Create Date: 2024-01-04 15:54:22.552822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4416fe65c2ad'
down_revision: Union[str, None] = '70dd9f3704e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
