"""Created customer data

Revision ID: 6e5360b71fbc
Revises: 30f7c7e61bff
Create Date: 2024-01-04 15:35:49.423308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5360b71fbc'
down_revision: Union[str, None] = '30f7c7e61bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('star_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'star_rating')
    # ### end Alembic commands ###
